ALTER TABLE `doctors_details` 
ADD COLUMN `phone` VARCHAR(20) DEFAULT NULL,
ADD COLUMN `address` TEXT DEFAULT NULL,
ADD COLUMN `biography` TEXT DEFAULT NULL,
ADD COLUMN `joining_date` DATA DEFAULT CURRENT_DATE,
ADD COLUMN `rating` DECIMAL(2,1) DEFAULT 5.0,
ADD COLUMN `reviews_count` INT DEFAULT 0;
